baseURL = 'https://simraseu.github.io/datamatiker-portfolio/'
languageCode = 'da-DK'
title = '4. Semester Portfolio - Simon'
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai"  # Eller "dracula", "rrt", etc.
    tabWidth = 4

[params]
  description = "Database & Storage + Data Science & Analytics"
  author = "Simon"
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowReadingTime = false
  ShowShareButtons = false
  ShowToc = true
  TocOpen = true
  # Disable auto-listing af sections på homepage
  mainSections = []
  defaultTheme = 'light'
  
  # Disable recent posts
  ShowRecentUpdates = false
  
 

[[menu.main]]
  name = "Forside"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Om Projektet"
  url = "/om-projektet/"
  weight = 2

[[menu.main]]
  name = "Læringsmål"
  url = "/laeringsmaal/"
  weight = 3

[[menu.main]]
  name = "Database & Storage"
  url = "/database/"
  weight = 4

[[menu.main]]
  name = "Data Science & Analytics"
  url = "/data-science/"
  weight = 5

[[menu.main]]
  name = "Vidensrejse"
  url = "/vidensrejse/"
  weight = 6

[[menu.main]]
  name = "Samlet Refleksion"
  url = "/refleksion/"
  weight = 7