baseURL = 'https://simraseu.github.io/datamatiker-portfolio/'
languageCode = 'da-DK'
title = '4. Semester Portfolio - Simon'
theme = 'PaperMod'

[params]
  description = "Database & Storage + Data Science & Analytics"
  author = "Simon"
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowReadingTime = false
  ShowShareButtons = false
  ShowToc = true
  TocOpen = false
  # Disable auto-listing af sections på homepage
  mainSections = []
  
  # Disable recent posts
  ShowRecentUpdates = false
  
 

[[menu.main]]
  name = "Forside"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Læringsmål"
  url = "/laeringsmaal/"
  weight = 2

[[menu.main]]
  name = "Blazor Projekt"
  url = "/blazor-projekt/"
  weight = 3

[[menu.main]]
  name = "Database & Storage"
  url = "/database/"
  weight = 4

[[menu.main]]
  name = "Data Science & Analytics"
  url = "/data-science/"
  weight = 5

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 6
